### ISSUE TITLE
Glass walls overlap the recipe for vanilla glass panes.

### ISSUE THREAD

**Issue by archonsd** [Nibaru/more_slabs_stairs_and_walls#4]
It's pretty challenging for most folks to overwrite recipes, so it would be a lot better to adjust the glass wall recipe to not overlap the vanilla glass pane recipe.

IMHO this is a bug, not a feature request.

**Comment by Nibaru** [comment]
Fair point, I updated the recipe in v2.0.1 to require glass planes as apposed to glass blocks.

**Comment by archonsd** [comment]
Are you taking the mod fabric-only?  I see the 2.0.1 fabric update on Curseforge but Forge's last update was 1.1.1.  Is a 2.0.1 for Forge coming?

**Comment by Nibaru** [comment]
Yes 2.0.0 update is in the works for forge.
